export const QUOTES: readonly string[] = [
  "Believe you can and you're halfway there.",
  "The only way to do great work is to love what you do.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Everything you've ever wanted is on the other side of fear.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Don't watch the clock; do what it does. Keep going.",
  "Act as if what you do makes a difference. It does.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "You are never too old to set another goal or to dream a new dream.",
  "What you get by achieving your goals is not as important as what you become.",
  "In the middle of every difficulty lies opportunity.",
  "Start where you are. Use what you have. Do what you can.",
  "Quality is not an act, it is a habit.",
  "The secret of getting ahead is getting started.",
  "Perseverance is not a long race; it is many short races one after the other.",
  "Small daily improvements over time lead to stunning results.",
  "Your attitude, not your aptitude, will determine your altitude.",
  "If you want to lift yourself up, lift up someone else.",
  "Strive not to be a success, but rather to be of value.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "It always seems impossible until it's done.",
  "The only person you are destined to become is the person you decide to be.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "You miss 100% of the shots you don't take.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "Whether you think you can or you think you can't, you're right.",
  "The man who moves a mountain begins by carrying away small stones.",
  "Courage is not having the strength to go on; it is going on when you don't have the strength.",
  "Do not wait to strike till the iron is hot; make it hot by striking.",
  "If you're going through hell, keep going.",
  "Our greatest glory is not in never falling, but in rising every time we fall.",
  "The best revenge is massive success.",
  "Don't let yesterday take up too much of today.",
  "It is during our darkest moments that we must focus to see the light.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Dream big and dare to fail.",
  "What we achieve inwardly will change outer reality.",
  "The harder the conflict, the greater the triumph.",
];